### ISSUE TITLE
Can't login title

### ISSUE THREAD

**Issue by bdonchenko** [SAP/ownid-demo#27]
Change to 'Can't login' which is what the user asked for.

![image.png](https://zenhub.wdf.sap.corp/images/5ebd66da010eda23834dcc74/5feb0f2e-ffc6-49d3-984e-c0d346aa2e81)

**Comment by giladvidal** [comment]
I guess this is the missing picture:
![image.png](https://images.zenhubusercontent.com/5fd2339be5d8bc1d8b14aa91/19b62734-e11d-4a48-b854-9f12d09bf5e0)

**Comment by akayomov** [comment]
Not clear description. I mean the task is done.
