### ISSUE TITLE
Add in profile page option to upgrade security

### ISSUE THREAD

**Issue by giladvidal** [SAP/ownid-demo#41]
Scenario:
- FIDO is disabled
- User register with basic authentication
- User login and view their profile
- If no FIDO in the account, let option to upgrade security

Technical:
- Using the override feature

**Comment by mike-cast** [comment]
### **Designs**
**Mobile** - https://www.figma.com/file/qlwlHQT5F5Y3ZIc7hKsmft/OwnID-Demo?node-id=1566%3A44
**Desktop** - https://www.figma.com/file/qlwlHQT5F5Y3ZIc7hKsmft/OwnID-Demo?node-id=1797%3A564

**Prototype** - https://www.figma.com/proto/qlwlHQT5F5Y3ZIc7hKsmft/OwnID-Demo?node-id=1364%3A0&viewport=1894%2C574%2C0.27169889211654663&scaling=min-zoom

**Screens**
Mobile
![Screen Shot 2021-01-19 at 5.16.47 PM.png](https://images.zenhubusercontent.com/5ff6187d83f4aa0d523061e4/d14dc8a7-8e82-438e-8e46-4df909ebe802)

Desktop
![Screen Shot 2021-01-19 at 5.17.02 PM.png](https://images.zenhubusercontent.com/5ff6187d83f4aa0d523061e4/ef5d4fa7-beeb-4b11-b920-26a7fb2cf43d)
