### ISSUE TITLE
Research: OwnID support for React Native

### ISSUE THREAD

**Issue by craimundo77** [SAP/ownid-demo#60]
Hi team,

We have a customer asking if we support OwnID in React Native applications. They are using gigya screensets in those apps and they are potentially interested in having OwnID there.

The scope of work is:
 - Having a sample react native app with the gigya screensets + OwnID and check if it works as expected.

There is a very old gigya sample reactive native app, in case it helps (https://github.com/gigya/ReactNative-Demo)

**Comment by Tony-Pa** [comment]
Result: 
We cannot use our UI SDK for React Native app as UI SDK requires browser global objects and DOM.

To make it work we should implement OwnID Module for React Native.
