### ISSUE TITLE
enable TFA icon

### ISSUE THREAD

**Issue by giladvidal** [SAP/ownid-demo#75]
currently 'enable TFA' appears as a text below the 3 icons.
Dor suggested to have that as a short text with icon as well (total is a list of 4 icons).

**Comment by mike-cast** [comment]
Designs
https://www.figma.com/file/qlwlHQT5F5Y3ZIc7hKsmft/OwnID-Demo?node-id=1364%3A0

Screens
![Screen Shot 2021-02-09 at 6.04.19 PM.png](https://images.zenhubusercontent.com/5ff6187d83f4aa0d523061e4/4dd3e24c-56ae-4480-9fc7-bc11ccf75c5b)

![Screen Shot 2021-02-09 at 6.04.28 PM.png](https://images.zenhubusercontent.com/5ff6187d83f4aa0d523061e4/e4b6219b-2094-4282-94d5-bb5279c6da98)
