### ISSUE TITLE
Login when not registered with OwnID

### ISSUE THREAD

**Issue by giladvidal** [SAP/ownid-demo#89]
Currently there are two options:
- in case the user entered email, we offer to link the account
- in case the user did not enter email, we ask to first create an account

Good enhancement would be to ask to enter email in case did not. Then,
- offer to link the account
- if not found display the existing message that ask to create account

**Comment by mike-cast** [comment]
**Message for each:**

Email entered but not recognized
"Login information is incorrect."

No email entered and not recognized by OwnID
"Please enter a valid email address."

**Designs**
mobile: https://www.figma.com/file/HMLGebZRMAeaGp62lK2zRs/Login?node-id=86%3A35
desktop: https://www.figma.com/file/HMLGebZRMAeaGp62lK2zRs/Login?node-id=131%3A0

**Screens**
![Screen Shot 2021-03-02 at 10.26.26 PM.png](https://images.zenhubusercontent.com/5ff6187d83f4aa0d523061e4/aefc3daa-f45e-4842-8a99-7d971797a451)

![Screen Shot 2021-03-02 at 10.26.08 PM.png](https://images.zenhubusercontent.com/5ff6187d83f4aa0d523061e4/e57fc923-f768-477d-b954-7738c050d5c6)

**Comment by mike-cast** [comment]
Updated designs~
