### ISSUE TITLE
Delete account

### ISSUE THREAD

**Issue by giladvidal** [SAP/ownid-demo#90]
Offer the user to delete the account.

- Click to delete
- Ask to approve
- Notify that account deleted followed by logout

**Comment by mike-cast** [comment]
@giladvidal This is for the demo site correct?

**Comment by giladvidal** [comment]
yes.

**Comment by mike-cast** [comment]
Design: https://www.figma.com/file/qlwlHQT5F5Y3ZIc7hKsmft/OwnID-Demo?node-id=1797%3A564

Prototype: https://www.figma.com/proto/qlwlHQT5F5Y3ZIc7hKsmft/OwnID-Demo?node-id=1364%3A0&viewport=457%2C772%2C0.41898560523986816&scaling=min-zoom

Screen:
![Screen Shot 2021-03-02 at 6.09.54 PM.png](https://images.zenhubusercontent.com/5ff6187d83f4aa0d523061e4/094c8bae-695b-46ca-92cc-179f75bc5acb)

**Comment by bdonchenko** [comment]
is it possible to do it from UI?

**Comment by giladvidal** [comment]
@bdonchenko - it is for the Demo so don't see why not.
